MVC-ChiefsCorner/MVC-ChiefsCorner/Areas/Admin/Controllers/AdminMenuController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MVC_ChiefsCorner.Context;
using MVC_ChiefsCorner.Models;

namespace MVC_ChiefsCorner.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]
    public class AdminMenuController : Controller
    {
        private readonly ChiefsCornerContext _context;

        public AdminMenuController(ChiefsCornerContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index()
        {
            var menuCategories = await _context.MenuCategories.ToListAsync();
            return View(menuCategories);
        }

        public async Task<IActionResult> Menu(int categoryId)
        {
            var menus = await _context.Menus.Where(m => m.MenuCategoryId == categoryId).ToListAsync();
            return View(menus);
        }

        public async Task<IActionResult> AddCategory()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddCategory(MenuCategory category, IFormFile? file)
        {
            if (ModelState.IsValid)
            {
                if (file != null && file.Length > 0)
                {
                    var fileName = Path.GetFileName(file.FileName);
                    var filePath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot\\images\\", fileName);
                    using (var stream = new FileStream(filePath, FileMode.Create))
                    {
                        await file.CopyToAsync(stream);
                    }
                    category.ImagePath = "/images/" + fileName;

                }
                else
                {
                    category.ImagePath = "/images/categories/bowlsCategory.png";
                }

                _context.MenuCategories.Add(category);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(category);
        }

        public async Task<IActionResult> EditCategory(int id)
        {
            var category = await _context.MenuCategories.FindAsync(id);
            if (category == null)
            {
                TempData["ErrorMessage"] = "Category not found.";
                return RedirectToAction(nameof(Index));
            }

            return View(category);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditCategory(int id, MenuCategory category, IFormFile? file)
        {
            if (id != category.Id)
            {
                TempData["ErrorMessage"] = "Invalid category ID.";
                return RedirectToAction(nameof(Index));
            }

            if (ModelState.IsValid)
            {
                try
                {
                    if (file != null && file.Length > 0)
                    {
                        var fileName = Path.GetFileName(file.FileName);
                        var filePath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot\\images\\", fileName);
                        using (var stream = new FileStream(filePath, FileMode.Create))
                        {
                            await file.CopyToAsync(stream);
                        }
                        category.ImagePath = "/images/" + fileName;
                    }
                    else
                    {
                        var existingCategory = await _context.MenuCategories.AsNoTracking().FirstOrDefaultAsync(a => a.Id == category.Id);
                        category.ImagePath = existingCategory.ImagePath;
                    }

                    _context.Update(category);
                    await _context.SaveChangesAsync();
                    TempData["SuccessMessage"] = "Category updated successfully.";
                    return RedirectToAction(nameof(Index));
                }
                catch (DbUpdateConcurrencyException)
                {
                    TempData["ErrorMessage"] = "An error occurred while updating the category.";
                    return RedirectToAction(nameof(Index));
                }
            }

            return View(category);
        }

        public async Task<IActionResult> DeleteCategory(int id)
        {
            var category = await _context.MenuCategories.FindAsync(id);
            if (category == null)
            {
                TempData["ErrorMessage"] = "Category not found.";
                return RedirectToAction(nameof(Index));
            }

            return View(category);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var category = await _context.MenuCategories.FindAsync(id);
            if (category == null)
            {
                TempData["ErrorMessage"] = "Category not found.";
                return RedirectToAction(nameof(Index));
            }

            _context.MenuCategories.Remove(category);
            await _context.SaveChangesAsync();

            TempData["SuccessMessage"] = "Category deleted successfully.";
            return RedirectToAction(nameof(Index));
        }




        public async Task<IActionResult> DetailsCategory(int id)
        {
            var category = await _context.MenuCategories.FindAsync(id);
            if (category == null)
            {
                TempData["ErrorMessage"] = "Category not found.";
                return RedirectToAction(nameof(Index));
            }

            return View(category);
        }




        //[ValidateAntiForgeryToken] niteliği, ASP.NET Core uygulamalarında Cross-Site Request Forgery(CSRF) saldırılarına karşı koruma sağlamak için kullanılır.CSRF saldırıları, yetkili bir kullanıcının tarayıcısını kötü niyetli bir web sitesine yönlendirerek, kullanıcının bilgilerini çalmak veya yetkili işlemler gerçekleştirmek amacıyla oturum açmasını sağlayan saldırılardır.

        //Bu nitelik, ASP.NET Core'un anti-CSRF mekanizmasını etkinleştirir. Bir form gönderildiğinde, bu nitelik otomatik olarak bir CSRF tokeni oluşturur ve form verileriyle birlikte gönderir. Sunucu tarafında, gelen isteğin token ile eşleşip eşleşmediği kontrol edilir. Eşleşme sağlanmazsa, istek reddedilir ve bir CSRF saldırısı olduğu düşünülür.
        public async Task<IActionResult> AddMenu()
        {
            ViewData["MenuCategories"] = await _context.MenuCategories.ToListAsync();
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddMenu(Menu menu, IFormFile? file)
        {
            if (ModelState.IsValid)
            {
                if (file != null && file.Length > 0)
                {
                    var fileName = Path.GetFileName(file.FileName);
                    var filePath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot\\images\\", fileName);
                    using (var stream = new FileStream(filePath, FileMode.Create))
                    {
                        await file.CopyToAsync(stream);
                    }
                    menu.ImagePath = "/images/" + fileName;
                }
                else
                {
                    menu.ImagePath = "/images/categories/bowlsCategory.png";
                }

                _context.Menus.Add(menu);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            ViewData["MenuCategories"] = await _context.MenuCategories.ToListAsync();
            return View(menu);

        }

        public async Task<IActionResult> EditMenu(int id)
        {
            var menu = await _context.Menus.FindAsync(id);
            if (menu == null)
            {
                TempData["ErrorMessage"] = "Menu not found.";
                return RedirectToAction(nameof(Index));
            }

            ViewData["MenuCategories"] = await _context.MenuCategories.ToListAsync();
            return View(menu);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditMenu(int id, Menu menu, IFormFile? file)
        {
            if (id != menu.Id)
            {
                TempData["ErrorMessage"] = "Invalid menu ID.";
                return RedirectToAction(nameof(Index));
            }

            if (ModelState.IsValid)
            {
                try
                {
                    if (file != null && file.Length > 0)
                    {
                        var fileName = Path.GetFileName(file.FileName);
                        var filePath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot\\images\\", fileName);
                        using (var stream = new FileStream(filePath, FileMode.Create))
                        {
                            await file.CopyToAsync(stream);
                        }
                        menu.ImagePath = "/images/" + fileName;
                    }
                    else
                    {
                        var existingMenu = await _context.Menus.AsNoTracking().FirstOrDefaultAsync(a => a.Id == menu.Id);
                        menu.ImagePath = existingMenu.ImagePath;
                    }

                    _context.Update(menu);
                    await _context.SaveChangesAsync();
                    TempData["SuccessMessage"] = "Menu updated successfully.";
                    return RedirectToAction(nameof(Index));
                }
                catch (DbUpdateConcurrencyException)
                {
                    TempData["ErrorMessage"] = "An error occurred while updating the menu.";
                    return RedirectToAction(nameof(Index));
                }
            }

MVC-ChiefsCorner/MVC-ChiefsCorner/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<AppUser> SignInManager


<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <title>Chef's Corner</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="" name="keywords">
    <meta content="" name="description">


    <!-- Favicon -->
    <link href="~/assets/img/favicon.ico" rel="icon">

    <!-- Google Web Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Heebo:wght@400;500;600&family=Nunito:wght@600;700;800&family=Pacifico&display=swap" rel="stylesheet">

    <!-- Icon Font Stylesheet -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet">

    <!-- Libraries Stylesheet -->
    <link href="~/assets/lib/animate/animate.min.css" rel="stylesheet">
    <link href="~/assets/lib/owlcarousel/assets/owl.carousel.min.css" rel="stylesheet">
    <link href="~/assets/lib/tempusdominus/css/tempusdominus-bootstrap-4.min.css" rel="stylesheet" />

    <!-- Customized Bootstrap Stylesheet -->
    <link href="~/assets/css/bootstrap.min.css" rel="stylesheet">

    <!-- Template Stylesheet -->
    <link href="~/assets/css/style.css" rel="stylesheet">

    <script src="https://kit.fontawesome.com/3d251c942d.js"></script>
</head>

<body>
    <div class="container-xxl bg-white p-0">
        <!-- Spinner Start -->
        <div id="spinner" class="show bg-white position-fixed translate-middle w-100 vh-100 top-50 start-50 d-flex align-items-center justify-content-center">
            <div class="spinner-border text-primary" style="width: 3rem; height: 3rem;" role="status">
                <span class="sr-only">Loading...</span>
            </div>
        </div>
        <!-- Spinner End -->
        <!-- Navbar & Hero Start -->
        <div class="container-xxl position-relative p-0">
            <nav class="navbar navbar-expand-lg navbar-dark bg-dark px-4 px-lg-5 py-3 py-lg-0">
                <a asp-action="Index" asp-controller="Home" class="navbar-brand p-0">
                    <img src="~/assets/img/logo.png" style="zoom: 1.3" alt="Logo">
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse">
                    <span class="fa fa-bars"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarCollapse">

                    
                    <div class="navbar-nav ms-auto py-0 pe-4">

                        <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        <a class="nav-link" asp-area="" asp-controller="Menu" asp-action="Index">Menu</a>
                        @if (SignInManager.IsSignedIn(User))
                        {
                            if (User.IsInRole("Admin"))
                            {
                                <a class="nav-link" asp-area="Admin" asp-controller="AdminMenu" asp-action="Index">Admin's Panel</a>
                            }
                            <a class="nav-link" asp-area="" asp-controller="Cart" asp-action="Index"><i class="fa-solid fa-cart-shopping fa-2x"></i></a>
                            <a class="nav-link" asp-area="" asp-controller="User" asp-action="Profile"><i class="fa-solid fa-user fa-2x"></i></a>
                            <a class="nav-link" asp-area="" asp-controller="User" asp-action="Logout"><i class="fa-solid fa-right-from-bracket fa-2x"></i></a>

                        }
                        else
                        {
                            <a class="nav-link" asp-area="" asp-controller="User" asp-action="SignUp">Sign Up</a>
                            <a class="nav-link" asp-area="" asp-controller="User" asp-action="SignIn">Sign In</a>
                        }


                    </div>
                    <a class="nav-link btn btn-primary py-2 px-4" asp-area="" asp-controller="Menu" asp-action="Index">Order</a>


                </div>
            </nav>

            <div class="container-xxl py-5 bg-dark">
            </div>
        </div>
        <!-- Navbar & Hero End -->
        @RenderBody()
        <!-- Footer Start -->
        <div class="container-fluid bg-dark text-light footer pt-5 mt-5 wow fadeIn" data-wow-delay="0.1s">
            <div class="container py-5">
                <div class="row g-5">
                    <div class="col-lg-3 col-md-6">
                        <h4 class="section-title ff-secondary text-start text-primary fw-normal mb-4">Company</h4>
                        <a class="btn btn-link" href="">About Us</a>
                        <a class="btn btn-link" href="">Contact Us</a>
                        <a class="btn btn-link" href="">Reservation</a>
                        <a class="btn btn-link" href="">Privacy Policy</a>
                        <a class="btn btn-link" href="">Terms & Condition</a>
                    </div>
                    <div class="col-lg-3 col-md-6">
                        <h4 class="section-title ff-secondary text-start text-primary fw-normal mb-4">Contact</h4>
                        <p class="mb-2"><i class="fa fa-map-marker-alt me-3"></i>1538/1. Sok, Isci Bloklari, Cankaya, Ankara, Turkey</p>
                        <p class="mb-2"><i class="fa fa-phone-alt me-3"></i>+90 505 475 5445</p>
                        <p class="mb-2"><i class="fa fa-envelope me-3"></i>info@chefscorner.com</p>
                        <div class="d-flex pt-2">
                            <a class="btn btn-outline-light btn-social" href=""><i class="fab fa-twitter"></i></a>
                            <a class="btn btn-outline-light btn-social" href=""><i class="fab fa-facebook-f"></i></a>
                            <a class="btn btn-outline-light btn-social" href=""><i class="fab fa-youtube"></i></a>
                            <a class="btn btn-outline-light btn-social" href=""><i class="fab fa-linkedin-in"></i></a>
                        </div>
                    </div>
                    <div class="col-lg-3 col-md-6">
                        <h4 class="section-title ff-secondary text-start text-primary fw-normal mb-4">Opening</h4>
                        <h5 class="text-light fw-normal">Monday - Saturday</h5>
                        <p>09AM - 09PM</p>
                        <h5 class="text-light fw-normal">Sunday</h5>
                        <p>10AM - 08PM</p>
                    </div>
                    <div class="col-lg-3 col-md-6">
                        <h4 class="section-title ff-secondary text-start text-primary fw-normal mb-4">Newsletter</h4>
                        <p>Dolor amet sit justo amet elitr clita ipsum elitr est.</p>
                        <div class="position-relative mx-auto" style="max-width: 400px;">
                            <input class="form-control border-primary w-100 py-3 ps-4 pe-5" type="text" placeholder="Your email">
                            <button type="button" class="btn btn-primary py-2 position-absolute top-0 end-0 mt-2 me-2">SignUp</button>
                        </div>
                    </div>
                </div>
            </div>
            <div class="container">
                <div class="copyright">
                    <div class="row">
                        <div class="col-md-6 text-center text-md-start mb-3 mb-md-0">
                        </div>
                        <div class="col-md-6 text-center text-md-end">
                            <div class="footer-menu">
                                <a href="">Home</a>
                                <a href="">Cookies</a>
                                <a href="">Help</a>
                                <a href="">FQAs</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Footer End -->
        <!-- Back to Top -->
        <a href="#" class="btn btn-lg btn-primary btn-lg-square back-to-top"><i class="bi bi-arrow-up"></i></a>
    </div>

    <!-- JavaScript Libraries -->
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/assets/lib/wow/wow.min.js"></script>
    <script src="~/assets/lib/easing/easing.min.js"></script>
    <script src="~/assets/lib/waypoints/waypoints.min.js"></script>
    <script src="~/assets/lib/counterup/counterup.min.js"></script>
    <script src="~/assets/lib/owlcarousel/owl.carousel.min.js"></script>
    <script src="~/assets/lib/tempusdominus/js/moment.min.js"></script>
    <script src="~/assets/lib/tempusdominus/js/moment-timezone.min.js"></script>
    <script src="~/assets/lib/tempusdominus/js/tempusdominus-bootstrap-4.min.js"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>

    <!-- Template Javascript -->
    <script src="~/assets/js/main.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>

</html>